# version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    ports:
      - '${PROMETHEUS_PORT}:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/etc/prometheus
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    ports:
      - '9100:9100'
    restart: unless-stopped
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    ports:
      - '${LOKI_PORT}:3100'
    user: "0:0"
    volumes:
      - ./loki-config.dev.yml:/etc/loki/local-config.yaml
      - ./data/loki:/loki-data
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.4.1
    container_name: promtail
    ports:
      - '9080:9080'
    volumes:
      - ./logs:/logs
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
