global:
  scrape_interval: 30s  # How frequently to scrape metrics

scrape_configs:
  - job_name: 'nestjs_app'
    metrics_path: '/metrics'
    scrape_timeout: 15s
    static_configs:
      - targets: ['10.151.0.71:3000'] # IP & Port of the NestJS app
  - job_name: 'node-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
